# /etc/nixos/configuration.nix
#
# Thin entry point. All real configuration lives in ./modules/*.
# The flake (flake.nix) points nixosSystem at this file; this file
# only wires the module tree together and pins stateVersion.
#
# unstablePkgs comes from flake.nix specialArgs — modules that need
# it declare it in their argument set.

{ config, pkgs, lib, unstablePkgs, concatPkg, ... }:

# ============================================================
# Custom packages
# ============================================================
# callPackage reads pkgs/<name>.nix as a function and passes it
# exactly the dependencies it asks for by name — no manual wiring.
# Future custom packages: one more line here per file in ./pkgs/.
#
# concatPkg is DIFFERENT: it comes from the upstream Concat flake
# (flake.nix specialArgs), not from ./pkgs/. No callPackage needed.
# To update Concat, bump the tag in flake.nix (`concat.url`), then
#   sudo nix flake update concat
let
  tolaria = pkgs.callPackage ./pkgs/tolaria.nix { };
  recordly = pkgs.callPackage ./pkgs/recordly.nix { };
  openwolf = pkgs.callPackage ./pkgs/openwolf.nix { };
in
{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config — do not edit // MINIMAL: KEEP ALWAYS — REGENERATE on laptop, do not copy UUIDs

    # ============================================================
    # core — KEEP ALL for minimal (cheap, needed to boot/login/network)
    # ============================================================
    ./modules/core/boot.nix        # KEEP MINIMAL — bootloader + kernel
    ./modules/core/nix.nix         # KEEP MINIMAL — flakes/caches; NOTE: set cudaSupport=false inside for fastest build
    ./modules/core/locale.nix      # KEEP MINIMAL — timezone/locale, tiny
    ./modules/core/network.nix     # KEEP MINIMAL — NetworkManager/hostname/ssh
    ./modules/core/dns.nix         # KEEP MINIMAL — systemd-resolved DoT, light
    ./modules/core/default-apps.nix # OPTIONAL — only xdg mime defaults, safe to drop for minimal
    ./modules/core/appimage.nix     # OPTIONAL — AppImage binfmt runner, safe to drop
    ./modules/core/flatpak.nix      # OPTIONAL — Flatpak sandboxed apps, safe to drop
    ./modules/core/fonts.nix        # KEEP — system fonts + defaults (bars/terms break without them)

    # ============================================================
    # hardware — only ssd is generic; rest are machine-specific
    # ============================================================
    ./modules/hardware/nvidia.nix       # desktop 1660 SUPER proprietary driver // MINIMAL/MACHINE-SPECIFIC: comment out on laptop, use nvidia-prime profile instead
    ./modules/hardware/audio.nix        # OPTIONAL — PipeWire/Bluetooth, drop = no sound but boots faster
    ./modules/hardware/ssd.nix          # KEEP MINIMAL — tmpfs/zram/trim, cheap + speeds up SSD
    ./modules/hardware/realtek-eee.nix  # MACHINE-SPECIFIC — only for RTL8111 enp5s0, drop on laptop
    ./modules/hardware/razer.nix        # OPTIONAL+MACHINE-SPECIFIC — only if Razer mouse/kb, safe to drop
    ./modules/hardware/amdgpu.nix       # AMD discrete GPU (RDNA3); INERT until amd-gpu.enable=true — see AMD PC section below
    ./modules/hardware/hardware-profiles.nix # OPTIONAL — portable GPU/VM toggles incl. laptop PRIME (see LAPTOP section below), cheap but safe to drop for minimal
    ./modules/hardware/laptop.nix      # LAPTOP: TLP+powertop+upower+thermald+suspend-then-hibernate+touchpad+wifi-powersave (needs laptop.enable=true below)
    ./modules/hardware/power-modes.nix # LAPTOP: laptop.powerMode powersave/balanced/performance — TLP tables + 80% charge cap

    # ============================================================
    # desktop — PICK ONE for minimal; each extra DE adds big build time
    # ============================================================
    ./modules/desktop/kde.nix           # HEAVY — Plasma6 full DE, keep only if KDE is the main DE
    ./modules/desktop/hyprland.nix      # HEAVY — Hyprland core, ALWAYS ON standalone; drop for minimal if KDE is kept (or vice versa)
    ./modules/system/desktop-extras.nix # OPTIONAL — all OFF by default, cheap to keep, safe to drop
    ./modules/system/btrfs.nix          # OPTIONAL — Btrfs root (scrub+snapshots); DISABLED by default, inert until btrfs-root.enable=true below
    ./modules/desktop/mango-dms.nix      # HEAVY — MangoWC from source + DMS, drop for minimal/fastest build
    ./modules/desktop/fury-dwm.nix       # OPTIONAL — experimental X11 dwm, safe to drop
    ./modules/desktop/xfce-chicago95.nix # OPTIONAL — 3rd DE, safe to drop for minimal
    ./modules/desktop/qylock.nix         # OPTIONAL — SDDM theme only, safe to drop
    ./modules/desktop/themes.nix         # OPTIONAL — cosmetic cursors/GTK, safe to drop
    ./modules/desktop/portals.nix        # KEEP with chosen DE — xdg portals/screenshare, keep 1 DE's portal

    # ============================================================
    # programs — shell only is minimal
    # ============================================================
    ./modules/programs/shell.nix         # KEEP MINIMAL — zsh/aliases, the login shell
    ./modules/programs/gaming.nix        # HEAVY — Steam/32-bit/proton, drop for minimal
    ./modules/programs/virtualisation.nix # HEAVY — QEMU/libvirt/podman, drop for minimal
    ./modules/programs/thunar.nix        # OPTIONAL — file manager, safe to drop
    ./modules/programs/firefox.nix       # OPTIONAL — 2nd browser, safe to drop if Brave/Zen cover it
    ./modules/programs/zen.nix           # OPTIONAL — currently empty/HM-managed, safe to drop import

    # ============================================================
    # AI — ALL HEAVY (CUDA/LLM), drop whole section for minimal
    # ============================================================
    # Local, mostly offline: ollama-cuda + open-webui + hermes, voice, OCR,
    # ComfyUI (module itself comes from the comfyui-nix FLAKE, see flake.nix).
    # Tuned for GTX 1660S 6GB — works on 1660 Ti laptop too, just heavy.
    ./modules/ai/ai-services.nix   # ollama-cuda + open-webui + hermes // HEAVY: #1 build-time cost, drop for minimal
    ./modules/ai/ai-stt.nix        # optional STT dictation (OFF by default) // OPTIONAL: drop for minimal
    ./modules/ai/ai-tts.nix        # optional offline TTS (OFF by default) // OPTIONAL: drop for minimal
    ./modules/ai/ai-ocr.nix        # optional screenshot OCR (OFF by default) // OPTIONAL: drop for minimal
    # ./modules/ai/comfyui.nix       # HEAVY+MACHINE-SPECIFIC: ComfyUI CUDA values, drop on laptop/minimal

    # ============================================================
    # services — ALL OPTIONAL, safe to drop for minimal
    # ============================================================
    ./modules/services/printing.nix  # OPTIONAL — CUPS, drop if no printer
    ./modules/services/searxng.nix   # OPTIONAL — localhost:8888 search + redis, drop for minimal
    ./modules/services/blocky.nix    # OPTIONAL — adblock DNS :53, drop for minimal

    # ============================================================
    # users & packages
    # ============================================================
    ./modules/users/users.nix             # KEEP MINIMAL — user fury/sudo, required to login
    ./modules/packages/system-packages.nix # HEAVY — ~150 pkgs/dev toolchains, biggest closure after AI, trim/drop for minimal
    ./modules/packages/brave-webgpu.nix   # comment out to drop the WebGPU build // HEAVY: custom Brave Vulkan build
    ./modules/packages/brave-fast.nix     # declarative brave-fast (daily Wayland build) // OPTIONAL: safe to drop
    ./modules/packages/apps-fixed.nix     # OPTIONAL — X11 wrappers (sioyek/upscayl/vesktop), safe to drop

    # ============================================================
    # unused modules — parked in modules/unused/, not deleted
    # ============================================================
    # Retired but kept: uncomment to bring one back, no re-download needed.
    # ----------------------------------------------------------------------
    # ./modules/unused/tide-island.nix # OPTIONAL — quickshell dynamic-island widget, parked 2026-09-23, not in use
    # ----------------------------------------------------------------------
  ];

  # ═══ CUSTOM PACKAGES (callPackage from ./pkgs/ + flake pkgs) — ALL OPTIONAL, drop for minimal ═══
  environment.systemPackages = [
    # markdown knowledge base manager (Tolaria AppImage, custom-wrapped)
    tolaria # OPTIONAL — drop for minimal
    # screen recorder + editor (Recordly AppImage, custom-wrapped — see pkgs/recordly.nix header for updates)
    recordly # OPTIONAL — drop for minimal
    # coding-agent memory CLI (OpenWolf npm tarball, node-wrapped — see pkgs/openwolf.nix header for updates)
    openwolf # OPTIONAL — drop for minimal
    # CapCut replacement, native Rust build from upstream flake (bump tag in flake.nix to update)
    concatPkg # HEAVY — Rust build from source, drop for minimal/fastest build
  ];
  # ============================================================
  # DNS — flip per network, then rebuild
  # ============================================================
  # "quad9" <-> "cloudflare" <-> "google" <-> "opendns" <-> "native"
  # (defined in modules/core/dns.nix). native = plain DHCP DNS, no DoT —
  # use on captive portals / work VPNs / networks where DoT is blocked.
  # then run: sudo nixos-rebuild switch --flake /etc/nixos#nixos
  # MAX PRIVACY with Quad9 (Swiss nonprofit, no query monetizing, GDPR):
  #   dns.provider = "quad9" + keep Blocky ON (trackers/ads die locally and
  #   never become upstream queries at all) + optional DNSSEC hardening in
  #   dns.nix ("no" -> "allow-downgrade" authenticates answers — breaks some
  #   unsigned domains, documented there). Quad9 validates DNSSEC server-side
  #   and sends no EDNS client subnet on 9.9.9.9. Avoid google/opendns here
  #   (commercial logging). This box already runs exactly this except DNSSEC.
  # ----------------------------------------------------------------------
  dns.provider = "google"; # use "cloudflare" or "google" if Quad9 blocks something // KEEP MINIMAL — just DNS choice, cheap
  # ----------------------------------------------------------------------
  # Blocky override for LONG stays on DoT-blocked networks (hotel week):
  # Blocky uses this verbatim instead of dns.provider. null (default) = auto-follow.
  # Quick stop / portal login? Don't override — disable Blocky instead (its import
  # below), portal pages need hijackable plain DNS. See blocky.nix header.
  # dns.upstreamOverride = [ "192.168.1.1" ]; # local router, plain (no DoT)
  # FALLBACK (DNS totally broken, get-online mode): comment the dns.nix import
  # above AND the blocky import AND this dns.provider line — all three at once.
  # dns-less alone FAILS evaluation (blocky + these options reference it).
  # Result: stock DHCP DNS like any plain distro — no DoT, no filtering.
  # ----------------------------------------------------------------------

  # ============================================================
  # hardware-profiles — DESKTOP (this machine: GTX 1660 SUPER)
  # ============================================================
  # MINIMAL on laptop: set this false, use the LAPTOP section below instead.
  # ----------------------------------------------------------------------
  hardware-profiles.nvidia.enable = true;       # this desktop // MACHINE-SPECIFIC: set false on laptop, desktop 1660 SUPER only
  # ----------------------------------------------------------------------

  # ============================================================
  # laptop — i7-10750H + GTX 1660 Ti Mobile (OFF on desktop)
  # ============================================================
  # On laptop: comment out nvidia.enable above, uncomment the lines below,
  # REGENERATE hardware-configuration.nix, rebuild.
  #
  # ── What are BusIDs? ──
  # The laptop has TWO GPUs (hybrid/Optimus): Intel UHD in the i7-10750H does
  # the desktop, GTX 1660 Ti sleeps until asked via `nvidia-offload <app>`.
  # NixOS needs the PCI addresses to bind the right driver to each chip:
  #   on laptop run: lspci | grep -E "VGA|3D"
  #   e.g. "00:02.0 VGA ... Intel UHD" -> "PCI:0:2:0"
  #        "01:00.0 VGA ... NVIDIA TU116" -> "PCI:1:0:0"
  # Wrong IDs = black screen or NVIDIA never wakes. Defaults below fit most
  # Intel+NVIDIA laptops including the i7-10750H + 1660 Ti — verify with lspci.
  # ----------------------------------------------------------------------
  # hardware-profiles.nvidia-prime.enable = true;  # laptop hybrid (set BusIDs!) // enable on laptop + set the two lines below
  # hardware-profiles.nvidia-prime.intelBusID = "PCI:0:2:0";   # i7-10750H UHD iGPU — verify: lspci | grep VGA
  # hardware-profiles.nvidia-prime.nvidiaBusID = "PCI:1:0:0";  # GTX 1660 Ti Mobile (TU116) — verify: lspci | grep 3D
  # hardware-profiles.intel.enable = true;          # Intel iGPU machine // enable ALONGSIDE nvidia-prime on the laptop (modesetting + VAAPI)
  # ----------------------------------------------------------------------
  #
  # ── PRIME mode: who renders? (rebuild + reboot to switch) ──
  # "offload" (default): Intel draws Hyprland/desktop, NVIDIA sleeps until needed.
  #   Use the GPU per-app, at full speed, with:  nvidia-offload steam
  #   (games, blender, CUDA, ollama — no rebuild needed, just prefix the app).
  # "sync": NVIDIA draws EVERYTHING incl. Hyprland. Max fps, no prefixes, but
  #   dGPU never sleeps — louder, hotter, ~1-2h battery. Plugged-in gaming only.
  # ----------------------------------------------------------------------
  # hardware-profiles.nvidia-prime.mode = "offload";  # or "sync" when plugged in for gaming
  # ----------------------------------------------------------------------
  #
  # ── HEAT NOTE (laptop CPU overheating): sync does NOT cool the CPU — the 1660 Ti
  # dumps 50-80W into the same shared heatpipes, so total heat goes UP. What cools
  # the i7-10750H: laptop.powerMode="balanced"/"powersave" (boost off on battery),
  # thermald (auto-on with intel.enable), clean fans + repaste, laptop cooler.
  #
  # ── LAPTOP power master switch ──
  # ----------------------------------------------------------------------
  # laptop.enable = true;      # TLP+powertop+upower+thermald+touchpad+sleep
  # laptop.powerMode = "balanced"; # powersave=lectures/flights, balanced=daily default, performance=plugged-in gaming/compile (see power-modes.nix header)
  # ----------------------------------------------------------------------

  # ============================================================
  # AMD PC — Ryzen 7 7700 + RX 7800 XT (OFF here, future machine)
  # ============================================================
  # On the AMD PC: set hardware-profiles.nvidia.enable=false above, comment out
  # ./modules/hardware/nvidia.nix in imports (it is UNCONDITIONAL — applies
  # whenever imported, unlike the gated modules), REGENERATE
  # hardware-configuration.nix, then uncomment below + rebuild.
  # The 7700's tiny Raphael iGPU needs nothing — the 7800 XT is primary, no
  # BusIDs/PRIME needed (that's laptop-hybrid only). RDNA3 uses the in-kernel
  # amdgpu driver — no proprietary blob like NVIDIA. For gaming this is the
  # simplest of the three machines: firmware + Mesa RADV + 32-bit, one switch.
  # (hardware-profiles.amdgpu.enable exists too but isn't needed — amd-gpu
  # covers driver binding + firmware + stack in one place.)
  # ----------------------------------------------------------------------
  # amd-gpu.enable = true;  # firmware+microcode+driver+early KMS+32-bit RADV (see modules/hardware/amdgpu.nix)
  # amd-gpu.rocm = true;    # HEAVY: ROCm/HIP compute for Blender/AI — OFF unless needed
  # ----------------------------------------------------------------------

  # ============================================================
  # hardware-profiles — OTHER MACHINES (all off here)
  # ============================================================
  # ----------------------------------------------------------------------
  # hardware-profiles.vm-guest.enable = true;       # QEMU/KVM guest // only inside a VM
  # hardware-profiles.local-hw-clock.enable = true; # dual-boot w/ Windows // only if dual-booting Windows
  # ----------------------------------------------------------------------

  # ============================================================
  # FILESYSTEM: noatime (cuts SSD write overhead)
  # ============================================================
  # Linux writes an atime update every time a file is READ — pure write
  # overhead on SSDs. options = [ "noatime" ] disables it.
  # Safe to declare here: fileSystems."/" MERGES across modules (only a second
  # device/fsType would conflict), so this appends to the block generated in
  # hardware-configuration.nix instead of replacing it. Uncomment + rebuild.
  # ----------------------------------------------------------------------
  # fileSystems."/".options = [ "noatime" ];
  # ----------------------------------------------------------------------

  # ============================================================
  # DESKTOP EXTRAS — enable per machine, rest stay off
  # ============================================================
  # MINIMAL: keep zram+fstrim (cheap), leave rest OFF/commented
  desktop-extras = {
  # ----------------------------------------------------------------------
    zram.enable = true;        # compressed RAM swap — good default // KEEP MINIMAL, cheap
    fstrim.enable = true;      # weekly SSD trim // KEEP MINIMAL, cheap
  # ----------------------------------------------------------------------
    # nh.enable = true;         # friendly rebuild helper (nixos-rebuild alt)
    # flatpak.enable = true;    # flathub(there is already a flatpak.nix)
    # printing.enable = true;   # CUPS
    # sane.enable = true;        # scanners
    # logitech.enable = true;    # Logitech peripherals
    # openrgb.enable = true;     # RGB control
    # plymouth.enable = true;    # boot splash
    # nfs.enable = true;         # NFS server
    # ly-greeter.enable = true;  # ⚠ Matrix login — DISABLES SDDM (kde.nix) first!
  # ----------------------------------------------------------------------
  };


  # ============================================================
  # BTRFS ROOT — disabled (ext4 in use here, see modules/system/btrfs.nix)
  # ============================================================
  # On the LAPTOP fresh install: format Btrfs from the start, then flip
  # enable + declarativeFilesystems to true. Gives rollback of bad rebuilds,
  # zstd compression (SSD space), monthly bitrot scrub, hourly /home snapshots.
  # Migration on ext4 requires reformat — cannot convert in place.
  # ----------------------------------------------------------------------
  btrfs-root = {
    enable = false;
    # declarativeFilesystems = true; # set true AFTER the Btrfs subvolumes exist
    # rootDevice = "/dev/disk/by-label/nixos"; # match `blkid` on the real disk
    # snapshots.enable = true;  # hourly snapper snapshots of /home
    # snapshotRoot = false;     # also snapshot / (needs /.snapshots subvol)
  };
  # ----------------------------------------------------------------------


  # ============================================================
  # AI — enable separately (matches AI imports section above)
  # ============================================================
  # MINIMAL: set both false/drop — ollama/piper pull models + CUDA, slowest builds
  # NOTE: the laptop 1660 Ti is same Turing TU116 as desktop 1660 SUPER, so CUDA/AI works there too — just heavy.
  # ----------------------------------------------------------------------
  ai-stt.enable = true;  # hyprwhspr-rs dictation (parakeet/whisper) // OPTIONAL: set false for minimal
  # ai-stt.cuda = true;    # NVIDIA acceleration (1660 SUPER) // HEAVY: works on laptop 1660 Ti too, keep OFF for minimal
  ai-tts.enable = true;  # piper-tts offline synthesis // OPTIONAL: set false for minimal
  # ai-ocr.enable = true;  # grim+slurp+tesseract screenshot OCR // OPTIONAL: leave off for minimal
  # ----------------------------------------------------------------------


  # This value determines the NixOS release from which the default
  # settings for stateful data were taken. Leave this at the release
  # version of the first install. Changing it will NOT upgrade.
  system.stateVersion = "26.05";
}
