# /etc/nixos/configuration.nix
#
# Thin entry point. All real configuration lives in ./modules/*.
# The flake (flake.nix) points nixosSystem at this file; this file
# only wires the module tree together and pins stateVersion.
#
# unstablePkgs comes from flake.nix specialArgs — modules that need
# it declare it in their argument set.

{ config, pkgs, lib, unstablePkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config — do not edit

    # --- core ---
    ./modules/core/boot.nix
    ./modules/core/nix.nix
    ./modules/core/locale.nix
    ./modules/core/network.nix
    ./modules/core/default-apps.nix

    # --- hardware ---
    ./modules/hardware/nvidia.nix
    ./modules/hardware/audio.nix
    ./modules/hardware/ssd.nix
    ./modules/hardware/realtek-eee.nix

    # --- desktop ---
    ./modules/desktop/kde.nix
    ./modules/desktop/xfce-chicago95.nix
    ./modules/desktop/qylock.nix
    ./modules/desktop/fonts.nix
    ./modules/desktop/themes.nix
    ./modules/desktop/portals.nix

    # --- programs ---
    ./modules/programs/shell.nix
    ./modules/programs/gaming.nix
    ./modules/programs/appimage.nix
    ./modules/programs/virtualisation.nix
    ./modules/programs/thunar.nix
    ./modules/programs/firefox.nix
    ./modules/programs/ai-services.nix

    # --- services ---
    ./modules/services/printing.nix
    ./modules/services/flatpak.nix

    # --- users & packages ---
    ./modules/users/users.nix
    ./modules/packages/system-packages.nix
    ./modules/packages/apps-fixed.nix
  ];

  # This value determines the NixOS release from which the default
  # settings for stateful data were taken. Leave this at the release
  # version of your first install. Changing it will NOT upgrade.
  system.stateVersion = "26.05";
}
