# /etc/nixos/configuration.nix
#
# Thin entry point. All real configuration lives in ./modules/*.
# The flake (flake.nix) points nixosSystem at this file; this file
# only wires the module tree together and pins stateVersion.
#
# unstablePkgs comes from flake.nix specialArgs — modules that need
# it declare it in their argument set.

{ config, pkgs, lib, unstablePkgs, ... }:

# ============================================================
# Custom packages
# ============================================================
# callPackage reads pkgs/<name>.nix as a function and passes it
# exactly the dependencies it asks for by name — no manual wiring.
# Future custom packages: one more line here per file in ./pkgs/.
let
  tolaria = pkgs.callPackage ./pkgs/tolaria.nix { };
in
{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config — do not edit

    # --- core ---
    ./modules/core/boot.nix
    ./modules/core/nix.nix
    ./modules/core/locale.nix
    ./modules/core/network.nix
    ./modules/core/dns.nix
    ./modules/core/default-apps.nix

    # --- hardware ---
    ./modules/hardware/nvidia.nix
    ./modules/hardware/audio.nix
    ./modules/hardware/ssd.nix
    ./modules/hardware/realtek-eee.nix
    ./modules/hardware/razer.nix

    # --- desktop ---
    ./modules/desktop/kde.nix
    # ── Hyprland core (ALWAYS ON — works standalone) ──
    ./modules/desktop/hyprland.nix

    # ── Tide Island (OPTIONAL — comment the next line to remove the island) ──
    ./modules/desktop/tide-island.nix

    # ── Portable hardware profiles (LinuxBeginnings port) ──
    ./modules/hardware/hardware-profiles.nix

    # ── Optional desktop services (LinuxBeginnings port, all OFF by default) ──
    ./modules/system/desktop-extras.nix


    ./modules/desktop/mango-dms.nix
    ./modules/desktop/fury-dwm.nix
    ./modules/desktop/xfce-chicago95.nix
    ./modules/desktop/qylock.nix
    ./modules/desktop/fonts.nix
    ./modules/desktop/themes.nix
    ./modules/desktop/portals.nix

    # --- programs ---
    ./modules/programs/shell.nix
    ./modules/programs/gaming.nix
    ./modules/programs/appimage.nix
    ./modules/programs/virtualisation.nix
    ./modules/programs/thunar.nix
    ./modules/programs/firefox.nix
    ./modules/programs/zen.nix
    ./modules/programs/ai-services.nix

    # --- services ---
    ./modules/services/printing.nix
    ./modules/services/flatpak.nix
    ./modules/services/searxng.nix
    ./modules/services/blocky.nix

    # --- users & packages ---
    ./modules/users/users.nix
    ./modules/packages/system-packages.nix
    ./modules/packages/brave-webgpu.nix   # comment out to drop the WebGPU build
    ./modules/packages/apps-fixed.nix
  ];

  # ═══ CUSTOM PACKAGES (callPackage from ./pkgs/) ═══
  environment.systemPackages = [
    # markdown knowledge base manager (Tolaria AppImage, custom-wrapped)
    tolaria
  ];
  # ═══ YOUR HARDWARE PROFILE (this machine) — flip for other hardware ═══
  # DNS flip: "quad9" <-> "cloudflare" <-> "google" (defined in modules/core/dns.nix)
  # then run: sudo nixos-rebuild switch --flake /etc/nixos#nixos
  dns.provider = "google"; # use "cloudflare" or "google" if Quad9 blocks something
  hardware-profiles.nvidia.enable = true;       # this desktop
  # hardware-profiles.nvidia-prime.enable = true;  # laptop hybrid (set BusIDs!)
  # hardware-profiles.amdgpu.enable = true;        # AMD GPU machine
  # hardware-profiles.intel.enable = true;          # Intel iGPU machine
  # hardware-profiles.vm-guest.enable = true;       # QEMU/KVM guest
  # hardware-profiles.local-hw-clock.enable = true; # dual-boot w/ Windows

  # ═══ DESKTOP EXTRAS — enable what you want, rest stay off ═══
  desktop-extras = {
    zram.enable = true;        # compressed RAM swap — good default
    fstrim.enable = true;      # weekly SSD trim
# appimage.enable = true; # DISABLED - use programs.appimage.binfmt
    # nh.enable = true;         # friendly rebuild helper (nixos-rebuild alt)
    # flatpak.enable = true;    # flathub(there is already a flatpak.nix)
    # printing.enable = true;   # CUPS
    # sane.enable = true;        # scanners
    # logitech.enable = true;    # Logitech peripherals
    # openrgb.enable = true;     # RGB control
    # plymouth.enable = true;    # boot splash
    # nfs.enable = true;         # NFS server
    # ly-greeter.enable = true;  # ⚠ Matrix login — DISABLES SDDM (kde.nix) first!
  };


  # This value determines the NixOS release from which the default
  # settings for stateful data were taken. Leave this at the release
  # version of your first install. Changing it will NOT upgrade.
  system.stateVersion = "26.05";
}
