# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dfc1e4e4-6a5f-4035-9540-11a4264edbf4";
      fsType = "ext4";
      # noatime: By default, Linux writes an update to disk every time a file is
      # read, just to record when it was last accessed. This disables that,
      # cutting out a large chunk of unnecessary write operations.
      # options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5660-B367";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  #swapDevices =
    #[ { device = "/dev/disk/by-uuid/25c2c9f4-c6c6-4c26-a611-fd61ba5efa21"; }
    #];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
